"""Inicial

Revision ID: d731bdb7f03e
Revises: 
Create Date: 2025-11-05 12:23:44.446474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd731bdb7f03e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('fecha_modificacion')

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    op.drop_table('user_credentials')
    # ### end Alembic commands ###
